### PR TITLE
Delete top-level __init__.py

### PR DESCRIPTION
**Pull request by rsokl**
Hello!

There is a `__init__.py` file in the top-level of this repo (`NeuralForceField/__init__.py`). This makes the entire repo look like a Python package, whereas `nff/` is the proper beginning of your Python package.

Thus this PR deletes `NeuralForceField/__init__.py`

### CODE REVIEW

**Comment by simonaxelrod** [comment]
Thanks for pointing this out! Will merge now

**Comment by rsokl** [comment]
@simonaxelrod did you mean to delete `EnsembleNFF`? (pushed 5 minutes ago)

https://github.com/learningmatter-mit/NeuralForceField/commit/06ec680678684c94a8837245098f9bdcd16a8f95

**Comment by simonaxelrod** [comment]
Yeah the class was defined twice for some reason. So I just deleted one of
the duplicates

**Comment by rsokl** [comment]
Gotchya. Just wanted to make sure! 😄

**Comment by simonaxelrod** [comment]
Yep - thanks for checking!

**Pull request merged**
